# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "30"

default_platform(:ios)

platform :ios do
  desc "Build by specifying configuration"
  private_lane :build do |options|
    build_app(
      clean: true,
      configuration: options[:configuration],
      skip_archive: true,
      skip_package_ipa: true,
      skip_package_pkg: true,
      xcodebuild_formatter: xcbeautify,
    )
  end

  lane :build_debug do
    setup_ci
    build(configuration: "Debug")
  end

  lane :build_release do
    setup_ci
    build(configuration: "Release")
  end
end
