# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "30"

default_platform(:ios)

platform :ios do
  desc "Build by specifying configuration"
  private_lane :build do |options|
    build_app(
      clean: true,
      configuration: options[:configuration],
      skip_package_ipa: true,
      skip_codesigning: true,
      xcodebuild_formatter: 'mint run xcbeautify',
      xcargs: "-allowProvisioningUpdates",
    )
  end

  lane :build_debug do
    setup_ci
    update_code_signing_settings(
      use_automatic_signing: true,
    )
    build(configuration: "Debug")
  end

  lane :build_release do |options|
    create_keychain(
      name: "mykeychain",
      password: ENV["KEYCHAIN_PASSWORD"],
      timeout: 1800
    )

    import_certificate(
      certificate_path: "./build_certificate.p12",
      certificate_password: ENV["P12_PASSWORD"],
      keychain_name: "mykeychain",
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    build(configuration: "Release")
  end
end
