# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-13
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin

    steps:
      - uses: actions/checkout@v3

      - name: xcode-select
        run: |
          sudo xcode-select -s '/Applications/Xcode_14.3.app'
          xcodebuild -version

      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      - name: Install Mint
        run: brew install mint

      - name: Cache Mint Packages
        id: cache-mint
        uses: actions/cache@v3
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - if: ${{ steps.cache-mint.outputs.cache-hit == 'false' }}
        name: Install Mint Packages
        run: mint bootstrap

      - name: List of mint packages
        continue-on-error: true
        run: mint list

      - name: Decode Certificate
        run: |
          echo "${{ secrets.CERTIFICATE_DEVELOPMENT }}" > certificate.p12.txt
          base64 --decode certificate.p12.txt > certificate.p12

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true
      
      - name: Build
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: bundle exec fastlane ios build_release
