# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: xcode-select
        run: sudo xcode-select -s '/Applications/Xcode_14.3.app'

      - name: Cache Mint
        env:
          MINT_PATH: .mint/lib
          MINT_LINK_PATH: .mint/bin
        uses: actions/cache@v3
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Mint Bootstrap
        run: mint bootstrap

      - name: build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build | xcbeautify
