# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-13
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin

    steps:
      - uses: actions/checkout@v3

      - name: xcode-select
        run: |
          sudo xcode-select -s '/Applications/Xcode_14.3.app'
          xcodebuild -version

      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      - name: Install Mint
        run: brew install mint

      - name: Cache Mint Packages
        id: cache-mint
        uses: actions/cache@v3
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - if: ${{ steps.cache-mint.outputs.cache-hit == 'false' }}
        name: Install Mint Packages
        run: mint bootstrap

      - name: List of mint packages
        continue-on-error: true
        run: mint list

      - name: Setup ruby and bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"
          bundler-cache: true

      - name: Import certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        run: echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o build_certificate.p12

      - name: Build
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: bundle exec fastlane ios build_release
