name: SwiftLint

on:
  push:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: '5.6.1'
          
          
      - name: GitHub Actions for SwiftLint
        uses: sinoru/actions-swiftlint@v6
      
      - name: GitHub Actions for SwiftLint with --strict
        uses: sinoru/actions-swiftlint@v6
        with:
          swiftlint-args: --strict
